-- SQL Insert Statements for Hotel Rooms --
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (41, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (41, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (41, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (41, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (41, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (42, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (42, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (42, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (42, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (42, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (43, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (43, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (43, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (43, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (43, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (44, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (44, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (44, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (44, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (44, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (45, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (45, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (45, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (45, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (45, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (46, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (46, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (46, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (46, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (46, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (47, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (47, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (47, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (47, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (47, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (48, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (48, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (48, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (48, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (48, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (49, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (49, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (49, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (49, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (49, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (50, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (50, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (50, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (50, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (50, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (51, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (51, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (51, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (51, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (51, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (52, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (52, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (52, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (52, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (52, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (53, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (53, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (53, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (53, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (53, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (54, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (54, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (54, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (54, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (54, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (55, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (55, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (55, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (55, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (55, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (56, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (56, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (56, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (56, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (56, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (57, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (57, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (57, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (57, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (57, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (58, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (58, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (58, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (58, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (58, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (59, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (59, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (59, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (59, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (59, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (60, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (60, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (60, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (60, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (60, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (61, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (61, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (61, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (61, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (61, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (62, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (62, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (62, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (62, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (62, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (63, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (63, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (63, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (63, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (63, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (64, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (64, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (64, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (64, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (64, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (65, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (65, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (65, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (65, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (65, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (66, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (66, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (66, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (66, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (66, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (67, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (67, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (67, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (67, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (67, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (68, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (68, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (68, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (68, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (68, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (69, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (69, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (69, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (69, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (69, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (70, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (70, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (70, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (70, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (70, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (71, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (71, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (71, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (71, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (71, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (72, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (72, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (72, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (72, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (72, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (73, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (73, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (73, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (73, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (73, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (74, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (74, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (74, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (74, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (74, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (75, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (75, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (75, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (75, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (75, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (76, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (76, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (76, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (76, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (76, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (77, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (77, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (77, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (77, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (77, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (78, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (78, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (78, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (78, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (78, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (79, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (79, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (79, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (79, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (79, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (80, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (80, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (80, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (80, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (80, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (81, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (81, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (81, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (81, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (81, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (82, 120, 1, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (82, 140, 2, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (82, 160, 3, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (82, 180, 4, 'City View', FALSE, '', 'WiFi, TV, Air Conditioning');
INSERT INTO Room (Hotel_ID, Price, Capacity, View_Type, Is_Extendible, Problems, Amenities) VALUES (82, 200, 5, 'Sea View', TRUE, '', 'WiFi, TV, Air Conditioning, Mini-bar');
